### ISSUE TITLE
AS.1: Documentation of shared implementation protocols

### ISSUE THREAD

**Issue by jmcmurry** [TranslatorIIPrototypes/operations#1]
**Issue Description:**

The documentation will include:
- [ ] [Guidelines for federation vs. integration to help Translator teams efficiently divide labor](https://github.com/TranslatorIIPrototypes/operations/issues/22)
- [ ] [A semantic model for Translator workflow operations to maintain provenance of a query by providing a controlled vocabulary to characterize workflow operations](https://github.com/TranslatorIIPrototypes/operations/issues/23)
- [ ] [Language of discourse for user-facing API for Translator operations](https://github.com/TranslatorIIPrototypes/operations/issues/24)
- [ ] [Identifier best-practices based on prior work and Translator need](https://github.com/TranslatorIIPrototypes/operations/issues/25)
- [ ] [API standards that define the interfaces used for interoperability between KPs, ARAs, the ARS, and other services](https://github.com/TranslatorIIPrototypes/operations/issues/26)
- [ ] [Protocols for handling user queries](https://github.com/TranslatorIIPrototypes/operations/issues/27)
- [ ] [Process for handling user feedback](https://github.com/TranslatorIIPrototypes/operations/issues/28)

**Comment by tursynay** [comment]
#Issue Description:# 

The documentation will include:
Guidelines for federation vs. integration to help Translator teams efficiently divide labor
A semantic model for Translator workflow operations to maintain provenance of a query by providing a controlled vocabulary to characterize workflow operations
Language of discourse for user-facing API for Translator operations
Identifier best-practices based on prior work and Translator need
API standards that define the interfaces used for interoperability between KPs, ARAs, the ARS, and other services
Protocols for handling user queries
Process for handling user feedback
(See also Governance above)

**Comment by tursynay** [comment]
Moved to new org: https://github.com/TranslatorSRI/Operations
